### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by jfl77** [kr-matthews/tic-tac-toe#1]
Hello,
I'm a Math/CS student and this is my first time contributing to a project. I would like to help you out with CSS styling, as well as with running some tests.

**Comment by kr-matthews** [comment]
Thanks for your interest, but I'm not sure this is a good place to help out. I'm more-or-less done with this project.

Yes, the styling and tests could be significantly improved. But everything else is also poorly done (as I can see looking back, after having done a few more projects), and any updates to the other aspects would require subsequently redoing the styling and tests anyway. So it doesn't seem worthwhile.

If you're not sure where to find another project to contribute to instead, consider reading [this](https://opensource.guide/how-to-contribute/#finding-a-project-to-contribute-to). I'm biased but I'd recommend the [world cube association](https://github.com/thewca/worldcubeassociation.org) -- they always need more help.
